### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#106]
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:761)
	at java.util.TimSort.mergeAt(TimSort.java:497)
	at java.util.TimSort.mergeCollapse(TimSort.java:424)
	at java.util.TimSort.sort(TimSort.java:210)
	at java.util.Arrays.sort(Arrays.java:1998)
	at java.util.Collections.sort(Collections.java:1900)
	at com.lgallardo.qbittorrentclient.be.onPostExecute(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Reported via Google Play Console!

**Comment by lgallard** [comment]
This is fixed in testing with the timestamp added on/completed on and with the size comparators

**Comment by lgallard** [comment]
Done!
