### ISSUE TITLE
Not working with Nexus 5X with Android 7

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#109]
App no longer works when I updated my Nexus 5X to Android 7.0. The app will open but as soon as I tap on a torrent that is downloading the app crashes. Maybe some testing with Android 7 is needed and an update to Fix the bug. 

Reported by Nathan (Google Play Console)

**Comment by lgallard** [comment]
Tested on Google Nexus 5.0 - Android 7.0 - API 24 (Genymotion). All working. I need more info. Checking the stack traces reported by the crash:


`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnCreateContextMenuListener(android.view.View$OnCreateContextMenuListener)' on a null object reference
	at android.app.Fragment.registerForContextMenu(Fragment.java:1892)
	at com.lgallardo.qbittorrentclient.cy.onCreateView(Unknown Source)
	at android.app.Fragment.performCreateView(Fragment.java:2352)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.BackStackRecord.run(BackStackRecord.java:815)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by lgallard** [comment]
Tested on Google Nexus 5.0 - Android 7.0 - API 24 (Android Emulator). All working ¬¬

**Comment by lgallard** [comment]
I haven't receive more reports about this. If the issue persists it can be reopen.
