### ISSUE TITLE
Fix issue “java.lang.NumberFormatException: Invalid float: "∞" in qbc

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#43]
This issue have been reported from Google Play Developer Console:

```java
java.lang.NumberFormatException: Invalid float: "∞"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:164)
	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
	at java.lang.Float.parseFloat(Float.java:306)
	at com.lgallardo.qbittorrentclient.TorrentRatioComparator.compare(TorrentRatioComparator.java:29)
	at com.lgallardo.qbittorrentclient.TorrentRatioComparator.compare(TorrentRatioComparator.java:15)
	at java.util.TimSort.binarySort(TimSort.java:261)
	at java.util.TimSort.sort(TimSort.java:186)
	at java.util.TimSort.sort(TimSort.java:169)
	at java.util.Arrays.sort(Arrays.java:2010)
	at java.util.Collections.sort(Collections.java:1883)
	at com.lgallardo.qbittorrentclient.MainActivity$qBittorrentTask.onPostExecute(MainActivity.java:2963)
	at com.lgallardo.qbittorrentclient.MainActivity$qBittorrentTask.onPostExecute(MainActivity.java:2728)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5725)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

**Comment by lgallard** [comment]
Fixed in testing!

**Comment by dipnaze32** [comment]
how did you fixed it

**Comment by lgallard** [comment]
@dipnaze32 https://github.com/lgallard/qBittorrent-Controller/commit/52e33aac2013644182ff98108dbdb9772d985067

qBittorrent sends "∞", the char for "infinite" that means a lot of time for ratio. So in the Torrent class I return a big value for ratio (1000) when qBittorrent returns "∞".

I hope it helps you!

**Comment by dipnaze32** [comment]
Thanks! But I have this error issue regarding invalid double: "-∞". which 
Double Vol;
/*Some double value of vol that start with -∞ and then changes to 65.9 to 200.90 range
*/
DecimalFormat df = new DecimalFormat("###.###");                   
                        Vol = Double.valueOf(df.format(Vol)); 

do you have any knowledge in the decimal format conversion? allowing the -∞ to convert to e.g. null value?

**Comment by lgallard** [comment]
You have to detect that condition and decide what to do with "∞" or "-∞",
which are not valid formats for decimal conversion. You cannot convert or
use a null value, you have to put a valid string like "1000", "100000",
etc. You must decide what infinite means to your app.

Regards,


Luis Gallardo
http://lgallardo.com

**Comment by dipnaze32** [comment]
Thanks you! That helps a lot. Appreciate!
