### ISSUE TITLE
Issue Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#73]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lgallardo.qbittorrentclient/com.lgallardo.qbittorrentclient.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.v7.widget.Toolbar
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.v7.widget.Toolbar
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:816)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
	at com.lgallardo.qbittorrentclient.MainActivity.onCreate(MainActivity.java:349)
	at android.app.Activity.performCreate(Activity.java:5264)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 24 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
	at android.content.res.Resources.loadDrawable(Resources.java:2152)
	at android.content.res.Resources.getDrawable(Resources.java:710)
	at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48)
	at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374)
	at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
	... 27 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2148)
	... 37 more

Reported through Google Developer Console

**Comment by lgallard** [comment]
This issue affected devices with Android version 4.4.x and below. It was fixed in app version 4.3.1 da70fb6be1fa4ea57c86b3e714214ab2b793595e

**Comment by wviana** [comment]
I'm getting this problem on my application too. I saw that you solved it downgrading the appCompat version, but There is another behaviour that is just working fine in `24.0.0` in my case. I add `vectorDrawables.useSupportLibrary = true` as you did. Checked you recent file and notice that there wasn't updated the library version. So you wasn't able to make it wok in newer version ? 

Sorry for disturbing, just found someone else with same problem as mine and decide to chat for maybe get some tip.

**Comment by lgallard** [comment]
Hi wviana, try downgrading the buildToolsVersion to 22 (in my case I'm using 22.0.1) and upgrade your support library to a newer one (in my case I'm using com.android.support:support-v4:23.2.1')

Regards,

**Comment by wviana** [comment]
@lgallard Thank you very very much. Solved it. I just update `buildToolsVersion` from `21.1.2` into `23.0.3`. With some other _proguard_ changes that I've made earlier this week, everything worked as expected. Thank you very very much.

**Comment by alexs-geronimo** [comment]
Great topic, thank you. @lgallard method worked (buildToolsVersion from 21.1.2 into 23.0.3)
